/**
 * ai-engine.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Pure Node.js LLM-powered AI engine for text2Viz.
 * Uses the Groq Cloud API (Llama 3.3 70B) for:
 *   1. Natural Language → SQL generation
 *   2. AI narrative insight generation
 *   3. Smart chart type recommendation
 *
 * All functions fall back gracefully if the API call fails.
 * ─────────────────────────────────────────────────────────────────────────────
 */

const Groq = require('groq-sdk');

// ── Model config ──────────────────────────────────────────────────────────────
const PRIMARY_MODEL   = 'llama-3.3-70b-versatile';   // Best quality
const FALLBACK_MODEL  = 'llama-3.1-8b-instant';       // Faster / cheaper
const MAX_TOKENS_SQL  = 512;
const MAX_TOKENS_INS  = 1024;
const MAX_TOKENS_CHART = 256;

// ── Shared Groq client (lazy-initialized) ─────────────────────────────────────
let _groqClient = null;
function getGroqClient(apiKey) {
  const key = apiKey || process.env.GROQ_API_KEY;
  if (!key) return null;
  // Re-create client if key has changed
  if (!_groqClient || _groqClient._apiKey !== key) {
    _groqClient = new Groq({ apiKey: key });
    _groqClient._apiKey = key;
  }
  return _groqClient;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Get schema text for a database from metadata.db
 */
async function getSchemaText(dbId, metaDb) {
  return new Promise((resolve, reject) => {
    metaDb.all(
      `SELECT table_name, column_name, data_type, primary_key, foreign_key, foreign_to_table, foreign_to_column
       FROM schema_metadata WHERE database_id = ? ORDER BY table_name, id`,
      [dbId],
      (err, rows) => {
        if (err) return reject(err);
        if (!rows || rows.length === 0) {
          return resolve(null); // Signal: no schema available
        }
        const schemaDict = {};
        rows.forEach(r => {
          if (!schemaDict[r.table_name]) schemaDict[r.table_name] = [];
          let colDesc = `${r.column_name} (${r.data_type})`;
          if (r.primary_key) colDesc += ' PRIMARY KEY';
          if (r.foreign_key) colDesc += ` REFERENCES ${r.foreign_to_table}(${r.foreign_to_column})`;
          schemaDict[r.table_name].push(colDesc);
        });
        let text = '';
        Object.entries(schemaDict).forEach(([tbl, cols]) => {
          text += `Table: ${tbl}\n`;
          cols.forEach(c => { text += `  - ${c}\n`; });
          text += '\n';
        });
        resolve(text);
      }
    );
  });
}

// ── 1. SQL Generation ─────────────────────────────────────────────────────────

/**
 * Generate SQL from a natural language question using Groq LLM.
 * Returns { sql, model, source } where source is 'llm' or 'fallback'.
 */
async function generateSql(question, dbId, metaDb, apiKey) {
  const groq = getGroqClient(apiKey);

  // Get schema from metadata db
  let schemaText = null;
  try {
    schemaText = await getSchemaText(dbId, metaDb);
  } catch (e) {
    console.warn('[AI Engine] Could not fetch schema:', e.message);
  }

  // Try LLM if we have a client and schema
  if (groq && schemaText) {
    try {
      const prompt = buildSqlPrompt(question, schemaText);
      const response = await groq.chat.completions.create({
        model: PRIMARY_MODEL,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.0,
        max_tokens: MAX_TOKENS_SQL,
        stop: ['```', ';--', '--'],
      });
      let sql = response.choices[0]?.message?.content?.trim() || '';
      sql = cleanSqlOutput(sql);
      if (sql && sql.toLowerCase().startsWith('select')) {
        console.log(`[AI Engine] SQL generated by LLM (${PRIMARY_MODEL})`);
        return { sql, model: PRIMARY_MODEL, source: 'llm' };
      }
    } catch (err) {
      console.warn('[AI Engine] Primary LLM SQL failed, trying fallback model:', err.message);
      // Try fallback model
      try {
        const response = await groq.chat.completions.create({
          model: FALLBACK_MODEL,
          messages: [{ role: 'user', content: buildSqlPrompt(question, schemaText) }],
          temperature: 0.0,
          max_tokens: MAX_TOKENS_SQL,
        });
        let sql = response.choices[0]?.message?.content?.trim() || '';
        sql = cleanSqlOutput(sql);
        if (sql && sql.toLowerCase().startsWith('select')) {
          console.log(`[AI Engine] SQL generated by fallback LLM (${FALLBACK_MODEL})`);
          return { sql, model: FALLBACK_MODEL, source: 'llm-fallback' };
        }
      } catch (e2) {
        console.warn('[AI Engine] Fallback LLM also failed:', e2.message);
      }
    }
  }

  // Rule-based fallback
  console.log('[AI Engine] Using rule-based SQL generator');
  const sql = generateSqlRuleBased(question);
  return { sql, model: null, source: 'rule-based' };
}

function buildSqlPrompt(question, schemaText) {
  return `You are a senior data analyst and SQLite SQL expert.
Convert the following natural language question into a clean, syntactically correct SQLite SQL query.

Database Schema:
${schemaText}

Question: "${question}"

Rules:
1. Respond ONLY with the raw SQL query. NO markdown, NO explanation, NO code fences.
2. Only write SELECT or WITH queries (read-only).
3. Do NOT add a semicolon at the end.
4. Use only table names and column names from the schema above.
5. Use SQLite syntax (strftime for dates, etc.).
6. Always use table aliases and descriptive column aliases for clarity.
7. Limit results to 100 rows unless the question asks for a specific count.

SQL:`;
}

function cleanSqlOutput(raw) {
  let sql = raw;
  // Remove markdown code fences
  sql = sql.replace(/^```(sql)?\s*/i, '').replace(/\s*```$/i, '');
  // Remove trailing semicolons
  sql = sql.replace(/;+\s*$/, '').trim();
  // Remove any preamble before SELECT/WITH
  const selectIdx = sql.search(/\bSELECT\b/i);
  const withIdx = sql.search(/\bWITH\b/i);
  const startIdx = Math.min(
    selectIdx >= 0 ? selectIdx : Infinity,
    withIdx >= 0 ? withIdx : Infinity
  );
  if (startIdx !== Infinity && startIdx > 0) {
    sql = sql.slice(startIdx);
  }
  return sql.trim();
}

// ── 2. Insight Generation ─────────────────────────────────────────────────────

/**
 * Generate rich AI narrative insights from query results using Groq LLM.
 * Falls back to rule-based stats if LLM is unavailable.
 */
async function generateInsights(question, columns, rows, apiKey) {
  const groq = getGroqClient(apiKey);

  if (groq && rows && rows.length > 0) {
    try {
      // Prepare a compact data sample for the LLM (max 20 rows)
      const sample = rows.slice(0, 20);
      const dataText = JSON.stringify(sample, null, 2);

      const prompt = `You are a senior data analyst providing business insights.

Question asked: "${question}"
Columns: ${columns.join(', ')}
Data Sample (${rows.length} total rows):
${dataText}

Write 4-5 concise, specific, actionable business insights from this data.
Format each insight as a bullet point. Do NOT include any emojis or icons.
Use **bold** for key metrics and numbers.
Be specific — reference actual values from the data.
Focus on patterns, top/bottom performers, trends, and anomalies.

Insights:`;

      const response = await groq.chat.completions.create({
        model: PRIMARY_MODEL,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.3,
        max_tokens: MAX_TOKENS_INS,
      });

      const rawInsights = response.choices[0]?.message?.content?.trim() || '';
      const insightLines = rawInsights
        .split('\n')
        .map(l => l.trim())
        .filter(l => l.length > 10 && !l.match(/^Insights?:/i));

      if (insightLines.length >= 2) {
        console.log('[AI Engine] Insights generated by LLM');
        return insightLines.slice(0, 6);
      }
    } catch (err) {
      console.warn('[AI Engine] LLM insight generation failed:', err.message);
    }
  }

  // Rule-based fallback
  return generateInsightsFallback(question, columns, rows);
}

function generateInsightsFallback(question, columns, rows) {
  if (!rows || rows.length === 0) return ['No data returned for this query.'];
  const insights = [];
  insights.push(`**${rows.length} records** returned for: "${question}".`);

  const numericCols = columns.filter(col => typeof rows[0][col] === 'number');
  numericCols.slice(0, 2).forEach(col => {
    const vals = rows.map(r => r[col]).filter(v => v !== null && v !== undefined && !isNaN(v));
    if (vals.length === 0) return;
    const sum = vals.reduce((a, b) => a + b, 0);
    const avg = (sum / vals.length).toFixed(2);
    const max = Math.max(...vals);
    const min = Math.min(...vals);
    insights.push(`**${col}**: Total = **${Number(sum.toFixed(2)).toLocaleString()}**, Average = **${avg}**, Peak = **${max.toLocaleString()}**`);
  });

  const firstCatCol = columns.find(col => typeof rows[0][col] === 'string');
  const firstNumCol = numericCols[0];
  if (firstCatCol && firstNumCol && rows.length > 0) {
    const topRow = rows.reduce((prev, cur) => (prev[firstNumCol] > cur[firstNumCol] ? prev : cur), rows[0]);
    const bottomRow = rows.reduce((prev, cur) => (prev[firstNumCol] < cur[firstNumCol] ? prev : cur), rows[0]);
    insights.push(`**Top performer:** ${topRow[firstCatCol]} with ${firstNumCol} = **${topRow[firstNumCol]?.toLocaleString?.() ?? topRow[firstNumCol]}**`);
    if (rows.length > 2) {
      insights.push(`**Lowest:** ${bottomRow[firstCatCol]} with ${firstNumCol} = **${bottomRow[firstNumCol]?.toLocaleString?.() ?? bottomRow[firstNumCol]}**`);
    }
  }
  return insights.slice(0, 5);
}

// ── 3. Chart Type Recommendation ──────────────────────────────────────────────

/**
 * Recommend the best chart type for a given question and dataset.
 * Uses LLM for smart recommendations or falls back to heuristics.
 */
async function recommendChart(question, columns, rows, apiKey) {
  const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#06b6d4', '#f97316'];
  const groq = getGroqClient(apiKey);

  const numericCols = columns.filter(col => rows.length > 0 && typeof rows[0][col] === 'number');
  const categoricalCols = columns.filter(col => !numericCols.includes(col));

  if (groq && rows && rows.length > 0) {
    try {
      const prompt = `You are a data visualization expert.

Question: "${question}"
Columns: ${columns.join(', ')}
Sample row: ${JSON.stringify(rows[0])}
Total rows: ${rows.length}
Numeric columns: ${numericCols.join(', ') || 'none'}
Text/Category columns: ${categoricalCols.join(', ') || 'none'}

Choose the BEST chart type from: bar, line, area, pie, scatter, table.
Respond ONLY with a JSON object like:
{"chart_type": "bar", "x_axis": "column_name", "y_axis": ["metric_col"], "reason": "one sentence"}

Use bar for comparisons, line/area for time trends, pie for proportions (<=8 categories), scatter for correlations, table for text-heavy results.`;

      const response = await groq.chat.completions.create({
        model: FALLBACK_MODEL, // Fast model for this quick decision
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.0,
        max_tokens: MAX_TOKENS_CHART,
      });

      const raw = response.choices[0]?.message?.content?.trim() || '';
      // Extract JSON from response
      const jsonMatch = raw.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        if (parsed.chart_type && parsed.x_axis && parsed.y_axis) {
          console.log(`[AI Engine] Chart type "${parsed.chart_type}" recommended by LLM. Reason: ${parsed.reason || 'N/A'}`);
          return {
            chart_type: parsed.chart_type,
            x_axis: parsed.x_axis,
            y_axis: Array.isArray(parsed.y_axis) ? parsed.y_axis : [parsed.y_axis],
            title: question,
            config: { colors: COLORS, reason: parsed.reason }
          };
        }
      }
    } catch (err) {
      console.warn('[AI Engine] LLM chart recommendation failed:', err.message);
    }
  }

  // Heuristic fallback
  return recommendChartHeuristic(question, columns, rows, numericCols, categoricalCols, COLORS);
}

function recommendChartHeuristic(question, columns, rows, numericCols, categoricalCols, colors) {
  const q = question.toLowerCase();

  if (categoricalCols.length >= 1 && numericCols.length >= 1) {
    if (q.includes('trend') || q.includes('month') || q.includes('time') || q.includes('date') || q.includes('year') || q.includes('weekly') || q.includes('daily')) {
      return { chart_type: 'line', x_axis: categoricalCols[0], y_axis: numericCols, title: question, config: { colors } };
    }
    if (q.includes('pie') || q.includes('proportion') || q.includes('share') || q.includes('distribution') || q.includes('breakdown')) {
      return { chart_type: 'pie', x_axis: categoricalCols[0], y_axis: numericCols.slice(0, 1), title: question, config: { colors } };
    }
    if (q.includes('area') || q.includes('cumulative') || q.includes('growth')) {
      return { chart_type: 'area', x_axis: categoricalCols[0], y_axis: numericCols, title: question, config: { colors } };
    }
    return { chart_type: 'bar', x_axis: categoricalCols[0], y_axis: numericCols, title: question, config: { colors } };
  }
  if (numericCols.length >= 2) {
    return { chart_type: 'scatter', x_axis: numericCols[0], y_axis: numericCols.slice(1), title: question, config: { colors } };
  }
  return { chart_type: 'table', x_axis: columns[0] || '', y_axis: columns.slice(1), title: question, config: { colors } };
}

// ── 4. SQL Validation ─────────────────────────────────────────────────────────

/**
 * Validate that SQL is safe (read-only, no destructive operations).
 */
function validateSql(sql) {
  if (!sql || typeof sql !== 'string') return { valid: false, error: 'Empty SQL query' };
  const normalized = sql.trim().toUpperCase();
  const forbidden = ['DROP ', 'DELETE ', 'INSERT ', 'UPDATE ', 'ALTER ', 'CREATE ', 'TRUNCATE ', 'REPLACE ', 'PRAGMA '];
  for (const kw of forbidden) {
    if (normalized.includes(kw)) {
      return { valid: false, error: `Forbidden SQL operation detected: ${kw.trim()}` };
    }
  }
  if (!normalized.startsWith('SELECT') && !normalized.startsWith('WITH')) {
    return { valid: false, error: 'Only SELECT queries are allowed' };
  }
  return { valid: true, error: null };
}

// ── Rule-Based SQL Generator (extended fallback) ──────────────────────────────

function generateSqlRuleBased(question) {
  const q = question.toLowerCase().trim();

  if (q === '__dashboard_reload__') {
    return 'SELECT * FROM sales ORDER BY sale_date DESC LIMIT 50';
  }

  if (q.includes('top') && q.includes('product') && (q.includes('revenue') || q.includes('sales') || q.includes('amount'))) {
    const m = q.match(/top\s+(\d+)/);
    const limit = m ? parseInt(m[1]) : 10;
    return `SELECT p.name AS product_name, c.name AS category, SUM(s.total_amount) AS total_revenue, COUNT(s.id) AS orders
FROM sales s JOIN products p ON s.product_id = p.id JOIN categories c ON p.category_id = c.id
GROUP BY p.id, p.name, c.name ORDER BY total_revenue DESC LIMIT ${limit}`;
  }
  if ((q.includes('sales') || q.includes('revenue') || q.includes('amount')) && (q.includes('category') || q.includes('categories'))) {
    return `SELECT c.name AS category_name, SUM(s.total_amount) AS total_sales, COUNT(s.id) AS order_count, AVG(s.total_amount) AS avg_order_value
FROM sales s JOIN products p ON s.product_id = p.id JOIN categories c ON p.category_id = c.id
GROUP BY c.id, c.name ORDER BY total_sales DESC`;
  }
  if ((q.includes('sales') || q.includes('revenue')) && (q.includes('month') || q.includes('monthly') || q.includes('trend') || q.includes('time'))) {
    let yearClause = '';
    if (q.includes('2025')) yearClause = "WHERE sale_date LIKE '2025%'";
    else if (q.includes('2026')) yearClause = "WHERE sale_date LIKE '2026%'";
    return `SELECT strftime('%Y-%m', sale_date) AS month, SUM(total_amount) AS revenue, COUNT(id) AS sales_count, AVG(total_amount) AS avg_sale
FROM sales ${yearClause} GROUP BY month ORDER BY month ASC`;
  }
  if ((q.includes('customer') || q.includes('customers')) && q.includes('city')) return `SELECT city, COUNT(id) AS customer_count FROM customers GROUP BY city ORDER BY customer_count DESC`;
  if ((q.includes('customer') || q.includes('customers')) && q.includes('country')) return `SELECT country, COUNT(id) AS customer_count FROM customers GROUP BY country ORDER BY customer_count DESC`;
  if ((q.includes('customer') || q.includes('customers')) && q.includes('segment')) return `SELECT segment, COUNT(id) AS customer_count FROM customers GROUP BY segment ORDER BY customer_count DESC`;
  if (q.includes('customer') || q.includes('customers')) return `SELECT name, email, city, country, segment, date(created_at) AS join_date FROM customers ORDER BY created_at DESC LIMIT 20`;
  if ((q.includes('product') || q.includes('products')) && (q.includes('stock') || q.includes('inventory'))) {
    return `SELECT p.name AS product_name, c.name AS category, p.stock_quantity, p.unit_price
FROM products p JOIN categories c ON p.category_id = c.id ORDER BY p.stock_quantity ASC`;
  }
  if (q.includes('product') || q.includes('products')) return `SELECT p.name AS product_name, c.name AS category, p.unit_price, p.stock_quantity FROM products p JOIN categories c ON p.category_id = c.id ORDER BY p.name ASC`;
  if (q.includes('employee') || q.includes('employees') || q.includes('staff')) {
    if (q.includes('department') || q.includes('dept')) return `SELECT department, COUNT(id) AS employee_count, AVG(salary) AS avg_salary FROM employees GROUP BY department ORDER BY employee_count DESC`;
    return `SELECT id, name, department, position, salary, hire_date FROM employees ORDER BY name ASC LIMIT 20`;
  }
  if (q.includes('supplier') || q.includes('suppliers')) return `SELECT id, name, country, contact_email FROM suppliers ORDER BY name ASC`;
  if (q.includes('inventory') || q.includes('warehouse') || q.includes('stock level')) {
    return `SELECT p.name AS product_name, i.quantity_in_stock, i.reorder_level, i.warehouse_location FROM inventory i JOIN products p ON i.product_id = p.id ORDER BY i.quantity_in_stock ASC`;
  }
  if (q.includes('campaign') || q.includes('marketing')) return `SELECT campaign_name, channel, budget, revenue_generated, start_date, end_date FROM marketing_campaigns ORDER BY revenue_generated DESC`;
  if (q.includes('support') || q.includes('ticket') || q.includes('tickets')) return `SELECT status, priority, COUNT(id) AS count FROM support_tickets GROUP BY status, priority ORDER BY count DESC`;
  if (q.includes('review') || q.includes('reviews') || q.includes('rating') || q.includes('ratings')) {
    return `SELECT p.name AS product_name, AVG(r.rating) AS avg_rating, COUNT(r.id) AS review_count FROM reviews r JOIN products p ON r.product_id = p.id GROUP BY p.id, p.name ORDER BY avg_rating DESC`;
  }
  if (q.includes('return') || q.includes('returns') || q.includes('refund') || q.includes('refunds')) return `SELECT reason, COUNT(id) AS return_count, SUM(refund_amount) AS total_refunded FROM returns GROUP BY reason ORDER BY return_count DESC`;
  if (q.includes('count') || q.includes('summary') || q.includes('overview') || q.includes('total')) {
    if (q.includes('sales') || q.includes('orders')) return `SELECT COUNT(*) AS total_orders, SUM(total_amount) AS total_revenue, AVG(total_amount) AS average_order_value, MAX(total_amount) AS highest_sale FROM sales`;
    if (q.includes('customers')) return `SELECT COUNT(*) AS total_customers, COUNT(DISTINCT city) AS cities_covered, COUNT(DISTINCT country) AS countries FROM customers`;
  }
  return `SELECT s.id AS transaction_id, c.name AS customer_name, p.name AS product_name, s.sale_date, s.quantity, s.total_amount
FROM sales s JOIN customers c ON s.customer_id = c.id JOIN products p ON s.product_id = p.id ORDER BY s.sale_date DESC LIMIT 50`;
}

async function generateDashboardInsights(dashboardName, dashboardDesc, widgetsData, apiKey) {
  const groq = getGroqClient(apiKey);
  if (groq && widgetsData && widgetsData.length > 0) {
    try {
      const widgetsSummaryText = widgetsData.map((w, index) => {
        const sampleRows = w.data ? w.data.slice(0, 10) : [];
        return `Widget #${index + 1}: "${w.question}" (Type: ${w.chart_type})
Data Sample (up to 10 rows):
${JSON.stringify(sampleRows, null, 2)}
`;
      }).join('\n\n');

      const prompt = `You are a Principal Business Intelligence Analyst.
You are reviewing a business dashboard named "${dashboardName}".
Dashboard Description: "${dashboardDesc || 'N/A'}"

Below are the queries and data samples displayed on this dashboard:
${widgetsSummaryText}

Write a professional executive summary and a list of 4-5 cross-cutting business insights for this dashboard.
Format your output as a clean Markdown document:
- Start with a section: "### Executive Summary" followed by a short paragraph.
- Then, add a section: "### Key Findings & Observations" followed by bullet points.
- Use **bold** for key numbers, metrics, and trends.
- Do NOT use emojis, lists of tables, or redundant introductions. Focus on cross-cutting trends (e.g. if one widget shows sales trends and another shows product category performance, connect the dots!).
- Be specific and use the actual values from the data.

Markdown Output:`;

      const response = await groq.chat.completions.create({
        model: PRIMARY_MODEL,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.4,
        max_tokens: MAX_TOKENS_INS,
      });

      return response.choices[0]?.message?.content?.trim() || 'No insights could be generated.';
    } catch (err) {
      console.warn('[AI Engine] Dashboard LLM insight generation failed, using fallback:', err.message);
    }
  }
  return generateDashboardInsightsFallback(dashboardName, widgetsData);
}

function generateDashboardInsightsFallback(dashboardName, widgetsData) {
  let summary = `### Executive Summary\nThis is a rule-based summary for the **${dashboardName}** dashboard. It contains **${widgetsData.length} widgets** analyzing active database tables.\n\n### Key Findings & Observations\n`;
  
  if (!widgetsData || widgetsData.length === 0) {
    return summary + `- No widgets are currently added to this dashboard. Go to the Edit Mode or Query Workspace to add some charts!`;
  }

  widgetsData.forEach((w) => {
    if (w.data && w.data.length > 0) {
      const numericCols = Object.keys(w.data[0]).filter(col => typeof w.data[0][col] === 'number');
      
      if (numericCols.length > 0) {
        const firstNum = numericCols[0];
        const vals = w.data.map(r => r[firstNum]).filter(v => typeof v === 'number');
        if (vals.length > 0) {
          const sum = vals.reduce((a, b) => a + b, 0);
          const avg = (sum / vals.length).toFixed(2);
          summary += `- For **"${w.question}"**: analyzed **${w.data.length} records**. The metric **${firstNum}** has a total sum of **${Number(sum.toFixed(2)).toLocaleString()}** and average of **${avg}**.\n`;
          return;
        }
      }
      summary += `- For **"${w.question}"**: returned **${w.data.length} rows** of data.\n`;
    } else {
      summary += `- For **"${w.question}"**: query returned empty results or failed to fetch.\n`;
    }
  });

  return summary;
}

// ── Exports ───────────────────────────────────────────────────────────────────

module.exports = {
  generateSql,
  generateInsights,
  recommendChart,
  validateSql,
  getSchemaText,
  generateSqlRuleBased,
  getGroqClient,
  generateDashboardInsights,
};

