import React, { useState } from 'react';
import { useStore } from '../store/useStore';
import { Key, Eye, EyeOff, Shield, User, Info, Database, Sparkles, Check, Zap } from 'lucide-react';

export default function Settings() {
  const { user, groqApiKey, setGroqApiKey } = useStore();
  const [key, setKey] = useState(groqApiKey);
  const [showKey, setShowKey] = useState(false);
  const [saved, setSaved] = useState(false);

  const isKeySet = key && key.startsWith('gsk_') && key.length > 20;

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();
    setGroqApiKey(key);
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
  };

  return (
    <div className="space-y-6 w-full">

      {saved && (
        <div className="p-4 bg-emerald-950/40 border border-emerald-500/30 text-emerald-200 text-sm rounded-xl flex items-center gap-2">
          <Check className="w-4 h-4 text-emerald-400" />
          Settings saved! AI-powered SQL generation is now active.
        </div>
      )}

      {/* Full-width 3-column layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
        
        {/* Left Columns (col-span-2): Settings Form & Cheat Sheet */}
        <div className="lg:col-span-2 space-y-6">

          {/* Status Banner */}
          <div className={`p-4 rounded-2xl border flex items-start gap-3 ${
            isKeySet
              ? 'bg-emerald-950/30 border-emerald-500/30'
              : 'bg-amber-950/20 border-amber-500/20'
          }`}>
            <Sparkles className={`w-5 h-5 shrink-0 mt-0.5 ${isKeySet ? 'text-emerald-400' : 'text-amber-400'}`} />
            <div>
              <p className={`font-bold text-sm ${isKeySet ? 'text-emerald-300' : 'text-amber-300'}`}>
                {isKeySet ? 'AI Engine Active — Llama 3.3 70B (Groq)' : 'Using Rule-Based Fallback — No Key Configured'}
              </p>
              <p className={`text-xs mt-0.5 ${isKeySet ? 'text-emerald-400/70' : 'text-amber-400/70'}`}>
                {isKeySet
                  ? 'SQL is generated by Llama 3.3 70B via Groq Cloud. Any natural language question will produce accurate, schema-aware SQL.'
                  : 'Enter your Groq API key below to unlock LLM-powered SQL generation for any question.'}
              </p>
            </div>
          </div>

          {/* API Key Form */}
          <div className="bg-darkSidebar/50 border border-darkBorder rounded-2xl p-6 shadow-sm">
            <h2 className="text-sm font-bold mb-1 flex items-center gap-2 text-slate-200 uppercase tracking-wider">
              <Key className="w-4 h-4 text-blue-500" />
              AI Engine Settings
            </h2>
            <p className="text-[11px] text-slate-500 mb-4">The key is stored in your backend .env and browser localStorage.</p>

            <form onSubmit={handleSave} className="space-y-4">
              <div>
                <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">
                  Groq Cloud API Key
                </label>
                <div className="relative">
                  <input
                    type={showKey ? 'text' : 'password'}
                    placeholder="gsk_..."
                    className="w-full bg-darkBg border border-darkBorder rounded-xl py-2.5 pl-3 pr-10 text-xs font-mono text-slate-200 placeholder-slate-600 focus:outline-none focus:border-blue-500"
                    value={key}
                    onChange={(e) => setKey(e.target.value)}
                  />
                  <button
                    type="button"
                    onClick={() => setShowKey(!showKey)}
                    className="absolute right-3 top-3.5 text-slate-500 hover:text-slate-300"
                  >
                    {showKey ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  </button>
                </div>

                {isKeySet && (
                  <p className="text-[11px] text-emerald-400 mt-1.5 flex items-center gap-1">
                    <Check className="w-3.5 h-3.5" /> Key configured — AI engine running
                  </p>
                )}

                <div className="flex gap-2.5 mt-4 p-3 bg-blue-950/20 border border-blue-500/10 rounded-xl text-xs text-slate-400">
                  <Info className="w-4 h-4 text-blue-500 shrink-0 mt-0.5" />
                  <div className="text-[11px] leading-relaxed">
                    <p className="font-bold text-slate-300 mb-0.5">Get a free Groq API key</p>
                    Sign up at <a href="https://console.groq.com" target="_blank" rel="noopener noreferrer" className="text-blue-400 underline font-semibold">console.groq.com</a> and generate an API key for free.
                    Groq Cloud gives you fast, free access to Llama 3.3 70B — the model powering this platform.
                  </div>
                </div>
              </div>

              <button
                type="submit"
                className="bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-5 rounded-xl text-xs transition-all shadow-md active:scale-95"
              >
                Save Settings
              </button>
            </form>
          </div>

          {/* Sample Questions to Try (Symmetric left column placement) */}
          <div className="bg-darkSidebar/30 border border-darkBorder rounded-2xl p-6 space-y-4 shadow-sm">
            <h2 className="text-sm font-bold flex items-center gap-2 text-slate-200 uppercase tracking-wider">
              <Database className="w-4 h-4 text-amber-500" />
              Sample Questions to Try
            </h2>
            <p className="text-slate-400 text-xs leading-relaxed">
              With the Groq API key active, you can ask <em>any</em> question in natural language. Click on a category card below to see analytical ideas:
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {[
                {
                  title: 'Sales Analysis',
                  questions: ['"Which products have declining sales?"', '"Compare Q1 vs Q2 revenue"']
                },
                {
                  title: 'Product Intelligence',
                  questions: ['"Show products with low stock and high demand"', '"What is the average rating per category?"']
                },
                {
                  title: 'Customer Insights',
                  questions: ['"Which customers have the most orders?"', '"Show churned customers by country"']
                },
                {
                  title: 'Operations & Logistics',
                  questions: ['"Which warehouse has the most inventory?"', '"Show return rate by category"']
                }
              ].map((group) => (
                <div 
                  key={group.title} 
                  className="bg-darkBg/40 hover:bg-darkBg border border-darkBorder/60 hover:border-slate-600 rounded-xl p-4 transition-all duration-300 space-y-2 group"
                >
                  <h4 className="text-[11px] font-bold text-slate-300 group-hover:text-blue-400 transition-colors">{group.title}</h4>
                  <div className="space-y-1 text-[11px]">
                    {group.questions.map((q, qIdx) => (
                      <p key={qIdx} className="text-slate-400 leading-normal italic hover:text-slate-200 transition-colors cursor-pointer select-none">• {q}</p>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* Right Column (col-span-1): User Profile & Engine Status info */}
        <div className="lg:col-span-1 space-y-6">
          
          {/* User Profile Card */}
          <div className="bg-darkSidebar/50 border border-darkBorder rounded-2xl p-6 shadow-sm">
            <h2 className="text-sm font-bold mb-4 flex items-center gap-2 text-slate-200 uppercase tracking-wider">
              <User className="w-4 h-4 text-emerald-500" />
              User Profile
            </h2>

            {user ? (
              <div className="space-y-4">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center font-bold text-emerald-400 text-sm">
                    {user.name.charAt(0).toUpperCase()}
                  </div>
                  <div>
                    <h3 className="font-bold text-slate-200 text-xs">{user.name}</h3>
                    <p className="text-[10px] text-slate-500">{user.email}</p>
                  </div>
                </div>

                <div className="border-t border-darkBorder/60 pt-4 space-y-2.5">
                  <div className="flex justify-between text-xs">
                    <span className="text-slate-400">User Role</span>
                    <span className="font-semibold text-slate-300 capitalize flex items-center gap-1">
                      <Shield className="w-3 h-3 text-blue-500" />
                      {user.role}
                    </span>
                  </div>
                  <div className="flex justify-between text-xs">
                    <span className="text-slate-400">AI Engine</span>
                    <span className={`font-semibold flex items-center gap-1 ${isKeySet ? 'text-emerald-400' : 'text-amber-400'}`}>
                      <Sparkles className="w-3 h-3" />
                      {isKeySet ? 'LLM Active' : 'Rule-based'}
                    </span>
                  </div>
                </div>
              </div>
            ) : (
              <p className="text-slate-500 text-xs">Not signed in.</p>
            )}
          </div>

          {/* Quick Status Card */}
          <div className="bg-gradient-to-br from-blue-950/30 to-purple-950/20 border border-blue-500/15 rounded-2xl p-5 shadow-sm">
            <div className="flex items-center gap-2 mb-3 border-b border-blue-500/10 pb-2">
              <Sparkles className="w-4 h-4 text-blue-400" />
              <span className="text-xs font-bold text-blue-300 uppercase tracking-wider">Groq Status</span>
            </div>
            <div className="space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-slate-400">Provider</span>
                <span className="text-slate-200 font-medium">Groq Cloud</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Model</span>
                <span className="text-slate-200 font-mono text-[10px]">llama-3.3-70b</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Status</span>
                <span className={`font-bold flex items-center gap-1 ${isKeySet ? 'text-emerald-400' : 'text-amber-400'}`}>
                  <span className={`w-1.5 h-1.5 rounded-full ${isKeySet ? 'bg-emerald-400 animate-pulse' : 'bg-amber-400 animate-pulse'}`}></span>
                  {isKeySet ? 'Online' : 'No Key'}
                </span>
              </div>
            </div>
          </div>

          {/* Model Info */}
          <div className="bg-darkSidebar/30 border border-darkBorder rounded-2xl p-6 shadow-sm">
            <h2 className="text-sm font-bold mb-4 flex items-center gap-2 text-slate-200 uppercase tracking-wider">
              <Zap className="w-4 h-4 text-purple-400" />
              AI Models Used
            </h2>
            <div className="space-y-3">
              {[
                { task: 'SQL Generation', model: 'llama-3.3-70b-versatile', badge: 'Primary', color: 'blue' },
                { task: 'Narrative Insights', model: 'llama-3.3-70b-versatile', badge: 'Primary', color: 'blue' },
                { task: 'Chart Recommendation', model: 'llama-3.1-8b-instant', badge: 'Fast', color: 'emerald' },
                { task: 'Rule-based SQL (offline)', model: 'Built-in JS heuristics', badge: 'Fallback', color: 'amber' },
              ].map(({ task, model, badge, color }) => (
                <div key={task} className="flex items-center justify-between py-2.5 px-3 bg-darkBg/60 border border-darkBorder/40 rounded-xl hover:border-slate-700 transition-colors">
                  <div>
                    <p className="text-xs font-semibold text-slate-300">{task}</p>
                    <p className="text-[9px] text-slate-500 font-mono mt-0.5">{model}</p>
                  </div>
                  <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full ${
                    color === 'blue' ? 'bg-blue-500/10 border border-blue-500/20 text-blue-400' :
                    color === 'emerald' ? 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400' :
                    'bg-amber-500/10 border border-amber-500/20 text-amber-400'
                  }`}>
                    {badge}
                  </span>
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
